compile:
	javac src/edu/wisc/cs/sdn/simpledns/*.java \
		  src/edu/wisc/cs/sdn/simpledns/packet/*.java

run:
	java -cp src edu/wisc/cs/sdn/simpledns/SimpleDNS -r 198.41.0.4 -e ec2.csv

clean:
	rm -rf src/edu/wisc/cs/sdn/simpledns/*.class \
		   src/edu/wisc/cs/sdn/simpledns/packet/*.class
